name: Code Review

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  issue_comment:
    types: [created]

jobs:
  review:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    uses: iamvikshan/.github/.github/workflows/pr-agent.yml@v0.36.1
    secrets:
      GEMINI: ${{ secrets.GEMINI }}